
export const Draggables = {
  PIECE: "piece",
};

export const emptyStartString = "emememememememememememememememememememememememememememememememememememememememememememememememememememememememememememememememem";
export const gameStartString = "brbnbbbqbkbbbnbrbpbpbpbpbpbpbpbpememememememememememememememememememememememememememememememememwpwpwpwpwpwpwpwpwrwnwbwqwkwbwnwr";